### ISSUE TITLE
Comments Hearts

### ISSUE THREAD

**Issue by Sz4by** [Ifarra/TikTokBoost#1]
not working automatically

**Comment by Ifarra** [comment]
can you provide picture? yes, it's not 100% automatic because sometimes you need to input the CAPTCHA

**Comment by Sz4by** [comment]
Well, I mean it doesn't automatically send the likes, it just puts the link and doesn't do anything, enter the comments and that's it

**Comment by Ifarra** [comment]
okay, ill try to fix it

**Comment by Ifarra** [comment]
@Sz4by Fixed, i also add auto solver so its fully automatic now, kinda

**Comment by Ifarra** [comment]
Updated

**Comment by Sz4by** [comment]
Thanks 😁😁

**Comment by Sz4by** [comment]
Can't make this work on your phone yet?

**Comment by Sz4by** [comment]
On termux?

**Comment by Ifarra** [comment]
unfortunately, selenium, the library that this script is based on, doesn't have any documentation for mobile use like termux

**Comment by Sz4by** [comment]
You don't know how to fix this on VPS ?
![Uploading Screenshot_20240812-115838.png…]()

**Comment by Sz4by** [comment]
And I open in browser and working 
![Uploading Screenshot_20240812-125022.png…]()

**Comment by Sz4by** [comment]
With the current update, it doesn't work properly without a browser, enter some errors and exit
